let testSnoozeAt=0;let audioContext=null,soundEnabled=false,ringInterval=null,testDeadline=0;
const activeAlarms=new Map(),armedDeadlines=new Map();
function validTime(value){return typeof value==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(value)}
function deadlineFields(date,time){return {deadline:date,deadlineTime:date&&validTime(time)?time:'',deadlineAt:date&&validTime(time)?new Date(date+'T'+time+':00').getTime():null}}
function normalizeDeadline(item){item.deadlineTime=validTime(item.deadlineTime)?item.deadlineTime:'';if(!item.deadline||!item.deadlineTime)item.deadlineAt=null;else if(!Number.isFinite(item.deadlineAt))item.deadlineAt=deadlineFields(item.deadline,item.deadlineTime).deadlineAt}
function backupDeadline(item){if(item.deadlineTime!==undefined&&item.deadlineTime!==''&&!validTime(item.deadlineTime))throw Error('无效截止时间');const data=deadlineFields(item.deadline||'',item.deadlineTime||'');if(item.deadlineAt!==undefined&&item.deadlineAt!==null){if(!Number.isFinite(item.deadlineAt))throw Error('无效截止时间');data.deadlineAt=item.deadlineAt}data.alarmSnoozeUntil=Number.isFinite(item.alarmSnoozeUntil)?item.alarmSnoozeUntil:null;data.alarmDismissedAt=Number.isFinite(item.alarmDismissedAt)?item.alarmDismissedAt:null;return data}
function deadlineTimestamp(item){return item.deadlineTime&&item.deadline?item.deadlineAt:null}
function remainingText(ms){const seconds=Math.max(0,Math.ceil(ms/1000)),days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60),rest=seconds%60;return (days?days+'天 ':'')+[hours,minutes,rest].map(n=>String(n).padStart(2,'0')).join(':')}
function trackingDeadline(item){if(!item.deadline)return null;return item.trackingDeadlineAt||deadlineTimestamp(item)||new Date(item.deadline+'T23:59:59.999').getTime()}
function backupTracking(item){const result={completedTimestamp:null,completionDeadline:null,snoozeHistory:[]};for(const field of ['completedTimestamp','completionDeadline'])if(item[field]!=null){if(!Number.isFinite(item[field])||item[field]<=0||item[field]>8640000000000000)throw Error('无效记录时间');result[field]=item[field]}if(item.snoozeHistory!==undefined){if(!Array.isArray(item.snoozeHistory)||item.snoozeHistory.length>10000)throw Error('无效延后记录');result.snoozeHistory=item.snoozeHistory.map(e=>{if(!e||!Number.isFinite(e.at)||e.at<=0||!Number.isInteger(e.seconds)||e.seconds<1||e.seconds>86400||!Number.isFinite(e.deadline))throw Error('无效延后记录');return {at:e.at,seconds:e.seconds,deadline:e.deadline}})}return result}
function delayText(item){if(item.pausedAt){const at=trackingDeadline(item);return at?'已暂停 · '+(item.pausedAt>at?'暂停时已超时 ':'剩余 ')+remainingText(Math.abs(at-item.pausedAt)):'已暂停'}if(item.submittedAt)return reviewDelay(item)+(item.reviewState==='waiting'?' · '+waitingText(item):'');if(item.done&&!Number.isFinite(item.completedTimestamp))return trackingDeadline(item)?'旧记录缺少完成时间，无法计算延迟':'';const at=item.done?item.completionDeadline:trackingDeadline(item);if(!at)return '';const ms=(item.done?item.completedTimestamp:Date.now())-at;return item.done?(ms>0?'延迟 '+remainingText(ms)+' 完成':'准时完成'):(ms>0?'已超时 '+remainingText(ms):'剩余 '+remainingText(-ms))}
function appendCountdown(item,container){const label=document.createElement('div');label.className='deadline-countdown delay-panel';label.dataset.countdownId=item.id;label.textContent=delayText(item);container.append(label);if(item.done&&Number.isFinite(item.completedTimestamp)){const date=document.createElement('div');date.className='completion-time';date.textContent='完成时间：'+new Date(item.completedTimestamp).toLocaleString('zh-CN',{hour12:false});container.append(date)}if(item.snoozeHistory?.length){const details=document.createElement('details');details.className='snooze-history';const summary=document.createElement('summary');summary.textContent='闹钟延后记录 · '+item.snoozeHistory.length+' 次';details.append(summary);for(const event of item.snoozeHistory){const line=document.createElement('p');line.textContent=new Date(event.at).toLocaleString('zh-CN',{hour12:false})+' · 延后 '+remainingText(event.seconds*1000);details.append(line)}container.append(details)}}
let ringtone='explosive';try{const saved=localStorage.getItem('daily-tasks-ringtone');if(['gentle','bright','urgent','explosive'].includes(saved))ringtone=saved}catch{}
function beep(){if(!audioContext||audioContext.state!=='running')return;const now=audioContext.currentTime;const settings={gentle:{count:2,spacing:.45,duration:.38,volume:.07,wave:'sine',frequencies:[523,659]},bright:{count:3,spacing:.32,duration:.26,volume:.12,wave:'sine',frequencies:[880,1175,1047]},urgent:{count:6,spacing:.2,duration:.16,volume:.15,wave:'triangle',frequencies:[880,1100]},explosive:{count:8,spacing:.18,duration:.17,volume:.2,wave:'sawtooth',frequencies:[650,1100]}}[ringtone];for(let n=0;n<settings.count;n++){const osc=audioContext.createOscillator(),gain=audioContext.createGain(),start=now+n*settings.spacing;osc.type=settings.wave;osc.frequency.setValueAtTime(settings.frequencies[n%settings.frequencies.length],start);if(ringtone==='explosive')osc.frequency.exponentialRampToValueAtTime(n%2?650:1100,start+.13);gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(settings.volume,start+.008);gain.gain.exponentialRampToValueAtTime(.001,start+settings.duration-.01);osc.connect(gain);gain.connect(audioContext.destination);osc.start(start);osc.stop(start+settings.duration)}}
async function enableSound(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error();audioContext??=new Audio();await audioContext.resume();if(audioContext.state!=='running')throw Error();soundEnabled=true;document.getElementById('sound-status').textContent='铃声已启用';beep();return true}catch{soundEnabled=false;document.getElementById('sound-status').textContent='无法启用声音，请检查浏览器声音设置';return false}}
function alarmKey(item){return item.id+':'+deadlineTimestamp(item)}
function alarmItems(){const result=[];for(const task of tasks){result.push({item:task,title:task.title});for(const child of task.children)result.push({item:child,title:task.title+' → '+child.title})}return result}
function refreshAlarmBanner(){const banner=document.getElementById('alarm-banner'),list=document.getElementById('alarm-items');list.replaceChildren();banner.hidden=!activeAlarms.size;for(const entry of activeAlarms.values()){const line=document.createElement('p');line.textContent=entry.title+(entry.item?' · '+delayText(entry.item):'');list.append(line)}if(activeAlarms.size&&soundEnabled&&!ringInterval){beep();ringInterval=setInterval(beep,1800)}if(!activeAlarms.size&&ringInterval){clearInterval(ringInterval);ringInterval=null}}
function tickAlarms(){const now=Date.now(),entries=alarmItems(),byId=new Map(entries.map(e=>[e.item.id,e.item]));for(const entry of entries){const before=entry.item.timeline?.length||0;syncTimeline(entry.item);if(entry.item.timeline.length!==before)save()}for(const label of document.querySelectorAll('[data-pause-id]')){const item=byId.get(label.dataset.pauseId);if(item)label.textContent=pauseText(item)}for(const label of document.querySelectorAll('[data-review-id]')){const item=byId.get(label.dataset.reviewId);if(item?.submittedAt)label.textContent='提交于 '+new Date(item.submittedAt).toLocaleString('zh-CN',{hour12:false})+' · '+reviewDelay(item)+' · '+waitingText(item)}for(const label of document.querySelectorAll('[data-countdown-id]')){const item=byId.get(label.dataset.countdownId);if(!item){label.textContent='';continue}label.textContent=delayText(item);label.classList.toggle('late',(item.done?item.completedTimestamp:now)>(item.done?item.completionDeadline:trackingDeadline(item)))}for(const [key,entry]of activeAlarms){if(entry.test)continue;const current=byId.get(entry.item.id);if(!current||current.done||current.pausedAt||current.reviewState==='waiting'||alarmKey(current)!==key||current.alarmDismissedAt===deadlineTimestamp(current))activeAlarms.delete(key)}for(const entry of entries){const item=entry.item,at=deadlineTimestamp(item);if(item.done||item.pausedAt||item.reviewState==='waiting'||!at)continue;const key=alarmKey(item);if(item.alarmSnoozeUntil&&item.alarmDismissedAt===at){if(item.alarmSnoozeUntil<=now){item.alarmDismissedAt=null;item.alarmSnoozeUntil=null;activeAlarms.set(key,entry);save()}else continue}if(at>now)armedDeadlines.set(item.id,at);else if(item.alarmDismissedAt!==at&&(armedDeadlines.get(item.id)===at||now-at<60000)){activeAlarms.set(key,entry);armedDeadlines.delete(item.id)}}if(testSnoozeAt&&now>=testSnoozeAt){activeAlarms.set('test',{test:true,title:'测试提醒 · 延后时间已到'});testSnoozeAt=0}const nextSnooze=Math.min(...entries.filter(e=>!e.item.done&&!e.item.pausedAt&&e.item.reviewState!=='waiting'&&e.item.alarmSnoozeUntil>now).map(e=>e.item.alarmSnoozeUntil),...(testSnoozeAt>now?[testSnoozeAt]:[]));const snoozeStatus=document.getElementById('snooze-status');snoozeStatus.hidden=!Number.isFinite(nextSnooze);if(Number.isFinite(nextSnooze))snoozeStatus.textContent='下次延后提醒：剩余 '+remainingText(nextSnooze-now);if(testDeadline){const label=document.getElementById('test-remaining');label.hidden=false;label.textContent='测试倒计时 '+remainingText(testDeadline-now);if(now>=testDeadline){activeAlarms.set('test',{test:true,title:'10 秒测试结束'});testDeadline=0;label.hidden=true}}refreshAlarmBanner()}
function initAlarms(){const picker=document.getElementById('ringtone');picker.value=ringtone;picker.onchange=async()=>{ringtone=picker.value;try{localStorage.setItem('daily-tasks-ringtone',ringtone)}catch{}await enableSound()};document.getElementById('enable-sound').onclick=async()=>{await enableSound();refreshAlarmBanner()};document.getElementById('test-countdown').onclick=async()=>{if(await enableSound()){testDeadline=Date.now()+10000;tickAlarms()}};document.getElementById('stop-alarm').onclick=()=>{for(const entry of activeAlarms.values())if(entry.item){entry.item.alarmDismissedAt=deadlineTimestamp(entry.item);entry.item.alarmSnoozeUntil=null;logEvent(entry.item,'stop_alarm','手动停止闹钟');}activeAlarms.clear();refreshAlarmBanner();save();render()};document.getElementById('snooze-five').onclick=()=>snoozeAlarms(5);document.getElementById('snooze-ten').onclick=()=>snoozeAlarms(10);document.getElementById('snooze-seconds').oninput=()=>document.getElementById('snooze-seconds').setCustomValidity('');document.getElementById('snooze-minutes').oninput=()=>document.getElementById('snooze-seconds').setCustomValidity('');document.getElementById('snooze-custom').onclick=()=>{const minutes=document.getElementById('snooze-minutes'),seconds=document.getElementById('snooze-seconds');seconds.setCustomValidity('');if(!minutes.checkValidity()){minutes.reportValidity();return}if(!seconds.checkValidity()){seconds.reportValidity();return}const total=Number(minutes.value)*60+Number(seconds.value);if(total<1||total>86400){seconds.setCustomValidity('请设置 1 秒至 24 小时的延后时间');seconds.reportValidity();return}snoozeAlarms(total/60)};setInterval(tickAlarms,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tickAlarms()});tickAlarms()}
document.addEventListener('DOMContentLoaded',initAlarms);

function snoozeAlarms(minutes){const totalSeconds=Math.round(minutes*60);if(!Number.isFinite(totalSeconds)||totalSeconds<1||totalSeconds>86400)return;const until=Date.now()+totalSeconds*1000;for(const entry of activeAlarms.values()){if(entry.test)testSnoozeAt=until;else{entry.item.alarmDismissedAt=deadlineTimestamp(entry.item);entry.item.alarmSnoozeUntil=until;entry.item.snoozeHistory??=[];logEvent(entry.item,'snooze','闹钟延后 '+remainingText(totalSeconds*1000));entry.item.snoozeHistory.push({at:Date.now(),seconds:totalSeconds,deadline:deadlineTimestamp(entry.item)})}}activeAlarms.clear();refreshAlarmBanner();save();render();tickAlarms()}
