let testSnoozeAt=0;let audioContext=null,soundEnabled=false,ringInterval=null,testDeadline=0;
const activeAlarms=new Map(),armedDeadlines=new Map();
function validTime(value){return typeof value==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(value)}
function deadlineFields(date,time){return {deadline:date,deadlineTime:date&&validTime(time)?time:'',deadlineAt:date&&validTime(time)?new Date(date+'T'+time+':00').getTime():null}}
function normalizeDeadline(item){item.deadlineTime=validTime(item.deadlineTime)?item.deadlineTime:'';if(!item.deadline||!item.deadlineTime)item.deadlineAt=null;else if(!Number.isFinite(item.deadlineAt))item.deadlineAt=deadlineFields(item.deadline,item.deadlineTime).deadlineAt}
function backupDeadline(item){if(item.deadlineTime!==undefined&&item.deadlineTime!==''&&!validTime(item.deadlineTime))throw Error('无效截止时间');const data=deadlineFields(item.deadline||'',item.deadlineTime||'');if(item.deadlineAt!==undefined&&item.deadlineAt!==null){if(!Number.isFinite(item.deadlineAt))throw Error('无效截止时间');data.deadlineAt=item.deadlineAt}data.alarmSnoozeUntil=Number.isFinite(item.alarmSnoozeUntil)?item.alarmSnoozeUntil:null;data.alarmDismissedAt=Number.isFinite(item.alarmDismissedAt)?item.alarmDismissedAt:null;return data}
function deadlineTimestamp(item){return item.deadlineTime&&item.deadline?item.deadlineAt:null}
function remainingText(ms){const seconds=Math.max(0,Math.ceil(ms/1000)),days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60),rest=seconds%60;return (days?days+'天 ':'')+[hours,minutes,rest].map(n=>String(n).padStart(2,'0')).join(':')}
function appendCountdown(item,container){if(item.done||!deadlineTimestamp(item))return;const label=document.createElement('div');label.className='deadline-countdown';label.dataset.countdownId=item.id;const ms=deadlineTimestamp(item)-Date.now();label.textContent=ms>0?'剩余 '+remainingText(ms):'已到截止时间';container.append(label)}
let ringtone='explosive';try{const saved=localStorage.getItem('daily-tasks-ringtone');if(['gentle','bright','urgent','explosive'].includes(saved))ringtone=saved}catch{}
function beep(){if(!audioContext||audioContext.state!=='running')return;const now=audioContext.currentTime;const settings={gentle:{count:2,spacing:.45,duration:.38,volume:.07,wave:'sine',frequencies:[523,659]},bright:{count:3,spacing:.32,duration:.26,volume:.12,wave:'sine',frequencies:[880,1175,1047]},urgent:{count:6,spacing:.2,duration:.16,volume:.15,wave:'triangle',frequencies:[880,1100]},explosive:{count:8,spacing:.18,duration:.17,volume:.2,wave:'sawtooth',frequencies:[650,1100]}}[ringtone];for(let n=0;n<settings.count;n++){const osc=audioContext.createOscillator(),gain=audioContext.createGain(),start=now+n*settings.spacing;osc.type=settings.wave;osc.frequency.setValueAtTime(settings.frequencies[n%settings.frequencies.length],start);if(ringtone==='explosive')osc.frequency.exponentialRampToValueAtTime(n%2?650:1100,start+.13);gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(settings.volume,start+.008);gain.gain.exponentialRampToValueAtTime(.001,start+settings.duration-.01);osc.connect(gain);gain.connect(audioContext.destination);osc.start(start);osc.stop(start+settings.duration)}}
async function enableSound(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error();audioContext??=new Audio();await audioContext.resume();if(audioContext.state!=='running')throw Error();soundEnabled=true;document.getElementById('sound-status').textContent='铃声已启用';beep();return true}catch{soundEnabled=false;document.getElementById('sound-status').textContent='无法启用声音，请检查浏览器声音设置';return false}}
function alarmKey(item){return item.id+':'+deadlineTimestamp(item)}
function alarmItems(){const result=[];for(const task of tasks){result.push({item:task,title:task.title});for(const child of task.children)result.push({item:child,title:task.title+' → '+child.title})}return result}
function refreshAlarmBanner(){const banner=document.getElementById('alarm-banner'),list=document.getElementById('alarm-items');list.replaceChildren();banner.hidden=!activeAlarms.size;for(const entry of activeAlarms.values()){const line=document.createElement('p');line.textContent=entry.title;list.append(line)}if(activeAlarms.size&&soundEnabled&&!ringInterval){beep();ringInterval=setInterval(beep,1800)}if(!activeAlarms.size&&ringInterval){clearInterval(ringInterval);ringInterval=null}}
function tickAlarms(){const now=Date.now(),entries=alarmItems(),byId=new Map(entries.map(e=>[e.item.id,e.item]));for(const label of document.querySelectorAll('[data-countdown-id]')){const item=byId.get(label.dataset.countdownId);if(!item||item.done){label.textContent='';continue}const ms=deadlineTimestamp(item)-now;label.textContent=ms>0?'剩余 '+remainingText(ms):'已到截止时间';label.classList.toggle('late',ms<=0)}for(const [key,entry]of activeAlarms){if(entry.test)continue;const current=byId.get(entry.item.id);if(!current||current.done||alarmKey(current)!==key||current.alarmDismissedAt===deadlineTimestamp(current))activeAlarms.delete(key)}for(const entry of entries){const item=entry.item,at=deadlineTimestamp(item);if(item.done||!at)continue;const key=alarmKey(item);if(item.alarmSnoozeUntil&&item.alarmDismissedAt===at){if(item.alarmSnoozeUntil<=now){item.alarmDismissedAt=null;item.alarmSnoozeUntil=null;activeAlarms.set(key,entry);save()}else continue}if(at>now)armedDeadlines.set(item.id,at);else if(item.alarmDismissedAt!==at&&(armedDeadlines.get(item.id)===at||now-at<60000)){activeAlarms.set(key,entry);armedDeadlines.delete(item.id)}}if(testSnoozeAt&&now>=testSnoozeAt){activeAlarms.set('test',{test:true,title:'测试提醒 · 延后时间已到'});testSnoozeAt=0}const nextSnooze=Math.min(...entries.filter(e=>!e.item.done&&e.item.alarmSnoozeUntil>now).map(e=>e.item.alarmSnoozeUntil),...(testSnoozeAt>now?[testSnoozeAt]:[]));const snoozeStatus=document.getElementById('snooze-status');snoozeStatus.hidden=!Number.isFinite(nextSnooze);if(Number.isFinite(nextSnooze))snoozeStatus.textContent='下次延后提醒：剩余 '+remainingText(nextSnooze-now);if(testDeadline){const label=document.getElementById('test-remaining');label.hidden=false;label.textContent='测试倒计时 '+remainingText(testDeadline-now);if(now>=testDeadline){activeAlarms.set('test',{test:true,title:'10 秒测试结束'});testDeadline=0;label.hidden=true}}refreshAlarmBanner()}
function initAlarms(){const picker=document.getElementById('ringtone');picker.value=ringtone;picker.onchange=async()=>{ringtone=picker.value;try{localStorage.setItem('daily-tasks-ringtone',ringtone)}catch{}await enableSound()};document.getElementById('enable-sound').onclick=async()=>{await enableSound();refreshAlarmBanner()};document.getElementById('test-countdown').onclick=async()=>{if(await enableSound()){testDeadline=Date.now()+10000;tickAlarms()}};document.getElementById('stop-alarm').onclick=()=>{for(const entry of activeAlarms.values())if(entry.item){entry.item.alarmDismissedAt=deadlineTimestamp(entry.item);entry.item.alarmSnoozeUntil=null;}activeAlarms.clear();refreshAlarmBanner();save()};document.getElementById('snooze-five').onclick=()=>snoozeAlarms(5);document.getElementById('snooze-ten').onclick=()=>snoozeAlarms(10);document.getElementById('snooze-seconds').oninput=()=>document.getElementById('snooze-seconds').setCustomValidity('');document.getElementById('snooze-minutes').oninput=()=>document.getElementById('snooze-seconds').setCustomValidity('');document.getElementById('snooze-custom').onclick=()=>{const minutes=document.getElementById('snooze-minutes'),seconds=document.getElementById('snooze-seconds');seconds.setCustomValidity('');if(!minutes.checkValidity()){minutes.reportValidity();return}if(!seconds.checkValidity()){seconds.reportValidity();return}const total=Number(minutes.value)*60+Number(seconds.value);if(total<1||total>86400){seconds.setCustomValidity('请设置 1 秒至 24 小时的延后时间');seconds.reportValidity();return}snoozeAlarms(total/60)};setInterval(tickAlarms,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tickAlarms()});tickAlarms()}
document.addEventListener('DOMContentLoaded',initAlarms);

function snoozeAlarms(minutes){const totalSeconds=Math.round(minutes*60);if(!Number.isFinite(totalSeconds)||totalSeconds<1||totalSeconds>86400)return;const until=Date.now()+totalSeconds*1000;for(const entry of activeAlarms.values()){if(entry.test)testSnoozeAt=until;else{entry.item.alarmDismissedAt=deadlineTimestamp(entry.item);entry.item.alarmSnoozeUntil=until}}activeAlarms.clear();refreshAlarmBanner();save();tickAlarms()}
