function logEvent(item,type,text,at=Date.now(),extra={}){item.timeline??=[];item.timeline.push({at,type,text,...extra})}
function localDay(at){const d=new Date(at);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function taskStatus(item){return item.done?'已完成':item.reviewState==='waiting'?'等待审核':'进行中'}
function syncTimeline(item){item.timeline??=[];if(!item.trackingStartedAt){item.trackingStartedAt=Date.now();logEvent(item,'tracking','开始记录时间线（此前历史不推算）')}const at=trackingDeadline(item);if(at&&at>=item.trackingStartedAt&&at<=Date.now()&&!item.timeline.some(e=>e.type==='deadline'&&e.deadline===at))logEvent(item,'deadline','到截止时间',at,{deadline:at})}
function changeTask(item,data){if(item.deadline!==data.deadline||item.deadlineTime!==data.deadlineTime){logEvent(item,'edit_deadline',`修改截止：${item.deadline||'未设置'} ${item.deadlineTime||''} → ${data.deadline||'未设置'} ${data.deadlineTime||''}`);item.alarmSnoozeUntil=null;item.alarmDismissedAt=null}else logEvent(item,'edit','修改任务内容');Object.assign(item,data)}
function newTracked(item){item.trackingStartedAt=Date.now();item.timeline=[];logEvent(item,'create','创建任务');return item}
function stopTaskAlarm(item,reason){item.alarmDismissedAt=deadlineTimestamp(item);item.alarmSnoozeUntil=null;activeAlarms.delete(alarmKey(item));logEvent(item,'stop_alarm',reason);refreshAlarmBanner()}
function submitReview(item){if(item.done||item.reviewState==='waiting')return;if(item.children?.some(c=>!c.done)){document.getElementById('message').textContent='请先完成或审核通过所有小任务，再提交总任务审核。';return}syncTimeline(item);item.reviewState='waiting';item.submittedAt=Date.now();item.submissionDeadline=trackingDeadline(item);logEvent(item,'submit','提交审核');stopTaskAlarm(item,'提交审核，自动停止闹钟');save();render()}
function rejectReview(item){if(item.reviewState!=='waiting')return;item.reviewWaitMs=(item.reviewWaitMs||0)+Math.max(0,Date.now()-item.submittedAt);logEvent(item,'reject','审核退回，继续重做');item.reviewState='working';item.submittedAt=null;item.submissionDeadline=null;save();render()}
function reviewDelay(item){const at=item.submissionDeadline;return at?(item.submittedAt>at?'提交延迟 '+remainingText(item.submittedAt-at):'准时提交'):'提交时未设截止'}
function waitingText(item){return '累计等待审核 '+remainingText((item.reviewWaitMs||0)+(item.reviewState==='waiting'?Math.max(0,Date.now()-item.submittedAt):0))}
function renderTimeline(item,container,period){const records=(item.timeline||[]).filter(e=>!period||localDay(e.at).startsWith(period)).slice().sort((a,b)=>a.at-b.at);if(!records.length)return;const section=document.createElement(period?'div':'details');section.className='task-timeline';const heading=document.createElement(period?'h4':'summary');heading.textContent='时间线 · '+records.length+' 条记录';section.append(heading);const list=document.createElement('ol');for(const e of records){const li=document.createElement('li');li.textContent=new Date(e.at).toLocaleString('zh-CN',{hour12:false})+' — '+e.text;list.append(li)}section.append(list);container.append(section)}
function appendReview(item,container){const area=document.createElement('div');area.className='review-controls';const state=document.createElement('strong');state.className='status-label';state.textContent=taskStatus(item);area.append(state);if(!item.done){const button=document.createElement('button');button.type='button';button.textContent=item.reviewState==='waiting'?'审核通过':'提交审核';button.onclick=()=>{if(item.reviewState==='waiting'){setCompleted(item,true);save();render()}else submitReview(item)};area.append(button);if(item.reviewState==='waiting'){const reject=document.createElement('button');reject.type='button';reject.textContent='退回重做';reject.onclick=()=>rejectReview(item);area.append(reject)}}container.append(area);if(item.submittedAt){const text=document.createElement('p');text.className='review-timing';text.dataset.reviewId=item.id;text.textContent='提交于 '+new Date(item.submittedAt).toLocaleString('zh-CN',{hour12:false})+' · '+reviewDelay(item)+' · '+waitingText(item);container.append(text)}renderTimeline(item,container)}
function renderTimelineReport(target,period){const entries=alarmItems().filter(e=>(e.item.timeline||[]).some(event=>localDay(event.at).startsWith(period)));if(!entries.length)return;const title=document.createElement('h3');title.textContent='任务过程与审核记录';target.append(title);const hint=document.createElement('p');hint.textContent='以下按操作发生日期汇总，包含未完成及等待审核任务；延迟按提交时间计算，等待审核单独统计。';target.append(hint);for(const e of entries){const block=document.createElement('div');block.className='report-group';const h=document.createElement('h4');h.textContent=e.title+' · '+taskStatus(e.item);block.append(h);const timing=document.createElement('p');timing.textContent=e.item.submittedAt?reviewDelay(e.item)+' · '+waitingText(e.item):delayText(e.item);block.append(timing);renderTimeline(e.item,block,period);target.append(block)}}
function backupWorkflow(item){const result={reviewState:item.reviewState==='waiting'?'waiting':'working',timeline:[],reviewWaitMs:0};for(const field of ['trackingStartedAt','submittedAt','submissionDeadline','reviewWaitMs'])if(item[field]!=null){if(!Number.isFinite(item[field])||item[field]<0||item[field]>8640000000000000)throw Error('无效审核时间');result[field]=item[field]}if(result.reviewState==='waiting'&&!result.submittedAt)throw Error('缺少提交时间');if(item.timeline!==undefined){if(!Array.isArray(item.timeline)||item.timeline.length>50000)throw Error('无效时间线');result.timeline=item.timeline.map(e=>{if(!e||!Number.isFinite(e.at)||e.at<=0||e.at>8640000000000000||typeof e.type!=='string'||typeof e.text!=='string'||e.text.length>1000||e.deadline!=null&&!Number.isFinite(e.deadline))throw Error('无效时间线');return {at:e.at,type:e.type,text:e.text,...(e.deadline!=null?{deadline:e.deadline}:{})}})}return result}
